local test = 'blah'
frame.display.clear()
frame.display.text('hello world', 50, 100)
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()
frame.display.show()